# Generated by Django 4.0.1 on 2022-06-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='avatar/null.png', upload_to='avatar/')),
            ],
        ),
    ]
