# Generated by Django 4.0.1 on 2022-06-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facemask', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
